network:
  version: 2
  renderer: networkd

  wifis:
    wlp6s0:
      dhcp4: no
      addresses:
       - 192.168.86.205/24
      nameservers:
        addresses:
         - 8.8.8.8
         - 8.8.4.4
        search:
         - home.arpa
      routes:
       - to: default
         via: 192.168.86.1
      access-points:
        "WIFI-SSID":
          auth:
            key-management: "psk"
            password: "WIFI_PASSWORD"

  ethernets:
    enp5s0f0:
      dhcp4: no
      addresses:
       - 172.16.1.205/24
      nameservers:
        search:
         - home.arpa