network:
  version: 2

  wifis:
    wlp6s0:
      dhcp4: true
      access-points:
        "WIFI-SSID":
          auth:
            key-management: "psk"
            password: "WIFI_PASSWORD"
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4

  ethernets:
    enp5s0f0:
      dhcp4: no
      addresses:
        - 172.16.0.10/24
      nameservers:
        addresses:
          - 172.16.0.5
