network:
  version: 2
  renderer: networkd

  wifis:
    wlp6s0:
      dhcp4: no
      addresses:
        - 192.168.86.253/24
      routes:
        - to: default
          via: 192.168.86.1
      access-points:
        "WIFI-SSID":
          auth:
            key-management: "psk"
            password: "WIFI_PASSWORD"
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4

  ethernets:
    enp5s0f0:
      dhcp4: no
      addresses:
        - 172.16.0.13/24
      nameservers:
        search:
          - home.arpa
        addresses:
          - 172.16.0.5
