network:
  version: 2

  wifis:
    wlp6s0:
      dhcp4: true
      access-points:
        "WIFI-SSID":
          auth:
            key-management: "psk"
            password: "WIFI_PASSWORD"

  ethernets:
    enp5s0f0:
      dhcp4: no
      addresses:
        - 172.16.0.11/16

